/**
 * Rule-based English → Spanish translation of USDA food names, so Spanish speakers can
 * search the full catalog ("pollo", "res", "queso"...). The output is meant for search
 * and a readable label, not for polished prose: unknown words (brands, cuts) stay as
 * they are and gender agreement is approximate. Mexican Spanish is preferred, with
 * synonyms from other regions added as search aliases in data/base-foods.csv instead.
 */

/** Multi-word expressions, matched before single words (longest first). */
export const PHRASES: Record<string, string> = {
  'separable lean and fat': 'carne magra y grasa separables',
  'separable lean only': 'solo carne magra',
  'separable fat': 'grasa separable',
  'meat and skin': 'carne y piel',
  'meat only': 'solo carne',
  'skin only': 'solo piel',
  'broilers or fryers': 'de engorde',
  'broiler or fryers': 'de engorde',
  'all grades': 'todos los grados',
  'trimmed to': 'recortado a',
  'with added salt': 'con sal añadida',
  'without added salt': 'sin sal añadida',
  'with salt': 'con sal',
  'without salt': 'sin sal',
  'added salt': 'sal añadida',
  'no salt added': 'sin sal añadida',
  'ready-to-eat': 'listo para comer',
  'ready-to-serve': 'listo para servir',
  'ready-to-drink': 'listo para beber',
  'ready-to-feed': 'listo para tomar',
  'ready-to-bake or -fry': 'listo para hornear o freír',
  'fast foods': 'comida rápida',
  'fast food': 'comida rápida',
  'mature seeds': 'semillas maduras',
  'new zealand': 'Nueva Zelanda',
  'prepared with water': 'preparado con agua',
  'prepared with milk': 'preparado con leche',
  'prepared from recipe': 'preparado en casa',
  'prepared-from-recipe': 'preparado en casa',
  'low sodium': 'bajo en sodio',
  'reduced sodium': 'bajo en sodio',
  'reduced fat': 'bajo en grasa',
  'low fat': 'bajo en grasa',
  'fat free': 'sin grasa',
  'sugar free': 'sin azúcar',
  'low calorie': 'bajo en calorías',
  'solids and liquids': 'sólidos y líquidos',
  'drained solids': 'sólidos escurridos',
  'whole milk': 'leche entera',
  'skim milk': 'leche descremada',
  'fruit juice': 'jugo de fruta',
  'orange juice': 'jugo de naranja',
  'apple juice': 'jugo de manzana',
  'ice cream': 'helado',
  'peanut butter': 'crema de cacahuate',
  'hot dog': 'salchicha',
  'french fries': 'papas a la francesa',
  'sweet potato': 'camote',
  'green beans': 'ejotes',
  'snap beans': 'ejotes',
  'black beans': 'frijoles negros',
  'kidney beans': 'frijoles rojos',
  'pinto beans': 'frijoles pintos',
  'chocolate chip': 'chispas de chocolate',
  'soy milk': 'leche de soya',
  'cottage cheese': 'queso cottage',
  'cream cheese': 'queso crema',
  'corn flakes': 'hojuelas de maíz',
  'pot roast': 'carne para asar',
  'infant formula': 'fórmula infantil',
  'table wine': 'vino de mesa',
  'eye of round': 'centro de pierna',
  'top round': 'pierna superior',
  'bottom round': 'pierna inferior',
  'top sirloin': 'sirloin superior',
  'short ribs': 'costillas cortas',
  'short loin': 'lomo corto',
  'ground beef': 'carne molida de res',
  'lean meat': 'carne magra',
  'human milk': 'leche materna',
  'baby food': 'comida para bebé',
  'coconut water': 'agua de coco',
  'coconut milk': 'leche de coco',
  'energy drink': 'bebida energética',
  'sports drink': 'bebida deportiva',
  'soy sauce': 'salsa de soya',
  'hot sauce': 'salsa picante',
  'olive oil': 'aceite de oliva',
  'dry heat': 'calor seco',
  'moist heat': 'calor húmedo',
  'pan-fried': 'frito en sartén',
  'pan-broiled': 'a la sartén',
  'deep fried': 'frito en aceite',
  'ready to eat': 'listo para comer',
  'egg white': 'clara de huevo',
  'egg yolk': 'yema de huevo',
  'whole egg': 'huevo entero',
};

/** Single words. Keys are lowercase; the value keeps its own capitalization. */
export const WORDS: Record<string, string> = {
  // Preparation and state
  fat: 'grasa',
  and: 'y',
  or: 'o',
  with: 'con',
  without: 'sin',
  of: 'de',
  from: 'de',
  for: 'para',
  in: 'en',
  to: 'a',
  no: 'sin',
  not: 'no',
  only: 'solo',
  all: 'todos',
  cooked: 'cocido',
  raw: 'crudo',
  lean: 'magro',
  separable: 'separable',
  trimmed: 'recortado',
  canned: 'enlatado',
  boneless: 'sin hueso',
  'bone-in': 'con hueso',
  roasted: 'asado',
  roast: 'asado',
  roasts: 'asados',
  frozen: 'congelado',
  dry: 'seco',
  dried: 'deshidratado',
  boiled: 'hervido',
  added: 'añadido',
  prepared: 'preparado',
  unprepared: 'sin preparar',
  drained: 'escurrido',
  fresh: 'fresco',
  imported: 'importado',
  whole: 'entero',
  braised: 'estofado',
  broiled: 'a la parrilla',
  grilled: 'a la plancha',
  fried: 'frito',
  baked: 'horneado',
  stewed: 'guisado',
  simmered: 'cocido a fuego lento',
  microwaved: 'en microondas',
  heated: 'calentado',
  unheated: 'sin calentar',
  toasted: 'tostado',
  smoked: 'ahumado',
  cured: 'curado',
  salted: 'salado',
  unsalted: 'sin sal',
  sweetened: 'endulzado',
  unsweetened: 'sin azúcar',
  enriched: 'enriquecido',
  unenriched: 'no enriquecido',
  fortified: 'fortificado',
  reduced: 'reducido',
  regular: 'regular',
  plain: 'natural',
  natural: 'natural',
  instant: 'instantáneo',
  refrigerated: 'refrigerado',
  pasteurized: 'pasteurizado',
  condensed: 'condensada',
  evaporated: 'evaporada',
  concentrate: 'concentrado',
  reconstituted: 'reconstituido',
  hydrogenated: 'hidrogenado',
  partially: 'parcialmente',
  commercially: 'comercialmente',
  homemade: 'casero',
  home: 'casero',
  recipe: 'receta',
  restaurant: 'restaurante',
  retail: 'comercial',
  industrial: 'industrial',
  composite: 'compuesto',
  mixed: 'mixto',
  mix: 'mezcla',
  blend: 'mezcla',
  includes: 'incluye',
  made: 'hecho',
  uncooked: 'sin cocinar',
  breaded: 'empanizado',
  breading: 'empanizado',
  crispy: 'crujiente',
  crunch: 'crujiente',
  chopped: 'picado',
  sliced: 'rebanado',
  slice: 'rebanada',
  slices: 'rebanadas',
  ground: 'molido',
  shredded: 'rallado',
  grated: 'rallado',
  mashed: 'puré',
  pureed: 'puré',
  strained: 'colado',
  sprouted: 'germinado',
  peeled: 'pelado',
  unpeeled: 'sin pelar',
  seedless: 'sin semilla',
  skinless: 'sin piel',
  stuffed: 'relleno',
  filling: 'relleno',
  topping: 'cobertura',
  spread: 'untable',
  powder: 'polvo',
  powdered: 'en polvo',
  granulated: 'granulado',
  liquid: 'líquido',
  liquids: 'líquidos',
  fluid: 'líquida',
  solids: 'sólidos',
  bottled: 'embotellado',
  carbonated: 'gaseosa',
  alcoholic: 'alcohólica',
  flavored: 'saborizado',
  flavor: 'sabor',
  flavors: 'sabores',
  style: 'estilo',
  type: 'tipo',
  variety: 'variedad',
  species: 'especies',
  all_varieties: 'todas las variedades',
  // Sizes and colors
  small: 'pequeño',
  petite: 'pequeño',
  large: 'grande',
  extra: 'extra',
  light: 'ligero',
  heavy: 'espesa',
  thin: 'delgado',
  thick: 'grueso',
  soft: 'suave',
  hard: 'duro',
  tender: 'tierno',
  half: 'mitad',
  low: 'bajo',
  high: 'alto',
  free: 'libre',
  white: 'blanco',
  red: 'rojo',
  green: 'verde',
  yellow: 'amarillo',
  black: 'negro',
  brown: 'integral',
  dark: 'oscuro',
  golden: 'dorado',
  sweet: 'dulce',
  sour: 'agrio',
  hot: 'picante',
  bitter: 'amargo',
  salty: 'salado',
  spicy: 'picante',
  mild: 'suave',
  // Meat, cuts, animals
  beef: 'res',
  pork: 'cerdo',
  chicken: 'pollo',
  turkey: 'pavo',
  lamb: 'cordero',
  veal: 'ternera',
  goat: 'cabra',
  duck: 'pato',
  goose: 'ganso',
  rabbit: 'conejo',
  venison: 'venado',
  bison: 'bisonte',
  buffalo: 'búfalo',
  game: 'caza',
  meat: 'carne',
  meats: 'carnes',
  steak: 'bistec',
  loin: 'lomo',
  tenderloin: 'filete',
  sirloin: 'sirloin',
  round: 'pierna',
  rib: 'costilla',
  ribs: 'costillas',
  chuck: 'diezmillo',
  shoulder: 'paleta',
  blade: 'paleta',
  arm: 'brazo',
  brisket: 'pecho',
  plate: 'falda',
  flank: 'falda',
  skirt: 'arrachera',
  shank: 'chambarete',
  neck: 'cuello',
  rump: 'cadera',
  leg: 'pierna',
  thigh: 'muslo',
  drumstick: 'muslo',
  breast: 'pechuga',
  wing: 'ala',
  wings: 'alas',
  back: 'espalda',
  liver: 'hígado',
  kidney: 'riñón',
  heart: 'corazón',
  tongue: 'lengua',
  giblets: 'menudencias',
  'by-products': 'subproductos',
  chops: 'chuletas',
  chop: 'chuleta',
  cuts: 'cortes',
  cut: 'corte',
  patty: 'hamburguesa',
  patties: 'hamburguesas',
  sausage: 'salchicha',
  sausages: 'salchichas',
  bacon: 'tocino',
  ham: 'jamón',
  pepperoni: 'pepperoni',
  salami: 'salami',
  bologna: 'mortadela',
  jerky: 'carne seca',
  skin: 'piel',
  bone: 'hueso',
  eye: 'centro',
  top: 'superior',
  bottom: 'inferior',
  center: 'centro',
  end: 'extremo',
  tip: 'punta',
  cap: 'tapa',
  lip: 'borde',
  'lip-on': 'con borde',
  inside: 'interior',
  outside: 'exterior',
  under: 'bajo',
  short: 'corto',
  flat: 'plano',
  clod: 'paleta',
  choice: 'choice',
  select: 'select',
  prime: 'prime',
  grades: 'grados',
  grade: 'grado',
  fryers: 'de engorde',
  broilers: 'de engorde',
  roasters: 'para rostizar',
  rotisserie: 'rostizado',
  stewing: 'para guisar',
  // Fish and seafood
  fish: 'pescado',
  salmon: 'salmón',
  tuna: 'atún',
  shrimp: 'camarón',
  crab: 'cangrejo',
  lobster: 'langosta',
  clam: 'almeja',
  clams: 'almejas',
  oyster: 'ostión',
  oysters: 'ostiones',
  squid: 'calamar',
  octopus: 'pulpo',
  cod: 'bacalao',
  trout: 'trucha',
  tilapia: 'tilapia',
  sardine: 'sardina',
  sardines: 'sardinas',
  anchovy: 'anchoa',
  anchovies: 'anchoas',
  herring: 'arenque',
  mackerel: 'macarela',
  halibut: 'halibut',
  catfish: 'bagre',
  snapper: 'huachinango',
  bass: 'lobina',
  mollusks: 'moluscos',
  crustaceans: 'crustáceos',
  mussels: 'mejillones',
  scallops: 'callos de hacha',
  atlantic: 'del Atlántico',
  pacific: 'del Pacífico',
  ocean: 'de mar',
  wild: 'silvestre',
  farmed: 'de cultivo',
  alaska: 'de Alaska',
  // Dairy and eggs
  milk: 'leche',
  cheese: 'queso',
  cheddar: 'cheddar',
  mozzarella: 'mozzarella',
  parmesan: 'parmesano',
  swiss: 'suizo',
  cottage: 'cottage',
  ricotta: 'ricotta',
  feta: 'feta',
  provolone: 'provolone',
  cream: 'crema',
  creams: 'cremas',
  butter: 'mantequilla',
  margarine: 'margarina',
  'margarine-like': 'tipo margarina',
  yogurt: 'yogur',
  kefir: 'kéfir',
  whey: 'suero',
  buttermilk: 'suero de leche',
  nonfat: 'sin grasa',
  lowfat: 'bajo en grasa',
  skim: 'descremada',
  egg: 'huevo',
  eggs: 'huevos',
  yolk: 'yema',
  human: 'humana',
  greek: 'griego',
  // Grains and bakery
  bread: 'pan',
  rolls: 'bollos',
  roll: 'bollo',
  bagel: 'bagel',
  bagels: 'bagels',
  muffin: 'panecillo',
  muffins: 'panecillos',
  biscuits: 'bísquets',
  crackers: 'galletas saladas',
  cookies: 'galletas',
  cookie: 'galleta',
  cake: 'pastel',
  cakes: 'pasteles',
  pie: 'pay',
  pies: 'pays',
  pastry: 'repostería',
  pastries: 'repostería',
  doughnuts: 'donas',
  brownies: 'brownies',
  pancakes: 'hot cakes',
  waffles: 'waffles',
  dough: 'masa',
  crust: 'base',
  flour: 'harina',
  wheat: 'trigo',
  rice: 'arroz',
  corn: 'maíz',
  oats: 'avena',
  oat: 'avena',
  oatmeal: 'avena',
  barley: 'cebada',
  rye: 'centeno',
  millet: 'mijo',
  quinoa: 'quinoa',
  buckwheat: 'trigo sarraceno',
  bulgur: 'bulgur',
  couscous: 'cuscús',
  bran: 'salvado',
  grain: 'grano',
  grains: 'granos',
  kernels: 'granos',
  cereal: 'cereal',
  cereals: 'cereales',
  granola: 'granola',
  pasta: 'pasta',
  noodles: 'fideos',
  noodle: 'fideo',
  spaghetti: 'espagueti',
  macaroni: 'macarrones',
  lasagna: 'lasaña',
  tortilla: 'tortilla',
  tortillas: 'tortillas',
  taco: 'taco',
  tacos: 'tacos',
  burrito: 'burrito',
  enchilada: 'enchilada',
  tamale: 'tamal',
  tamales: 'tamales',
  pizza: 'pizza',
  sandwich: 'sándwich',
  popcorn: 'palomitas',
  pretzels: 'pretzels',
  chips: 'chips',
  chip: 'chip',
  'gluten-free': 'sin gluten',
  // Legumes, nuts and seeds
  beans: 'frijoles',
  bean: 'frijol',
  lentils: 'lentejas',
  chickpeas: 'garbanzos',
  peas: 'chícharos',
  soy: 'soya',
  soybean: 'soya',
  soybeans: 'frijol de soya',
  soymilk: 'leche de soya',
  tofu: 'tofu',
  tempeh: 'tempeh',
  hummus: 'hummus',
  nuts: 'nueces',
  peanut: 'cacahuate',
  peanuts: 'cacahuates',
  almond: 'almendra',
  almonds: 'almendras',
  walnuts: 'nueces',
  cashews: 'nueces de la India',
  pistachios: 'pistaches',
  pecans: 'nueces pecanas',
  hazelnuts: 'avellanas',
  macadamia: 'macadamia',
  seeds: 'semillas',
  seed: 'semilla',
  sunflower: 'girasol',
  sesame: 'ajonjolí',
  flax: 'linaza',
  chia: 'chía',
  coconut: 'coco',
  // Fruit
  fruit: 'fruta',
  fruits: 'frutas',
  apple: 'manzana',
  apples: 'manzanas',
  banana: 'plátano',
  bananas: 'plátanos',
  orange: 'naranja',
  oranges: 'naranjas',
  lemon: 'limón',
  lemons: 'limones',
  lime: 'limón verde',
  limes: 'limones verdes',
  grapefruit: 'toronja',
  grape: 'uva',
  grapes: 'uvas',
  strawberry: 'fresa',
  strawberries: 'fresas',
  blueberry: 'arándano',
  blueberries: 'arándanos',
  raspberry: 'frambuesa',
  raspberries: 'frambuesas',
  blackberries: 'zarzamoras',
  cranberry: 'arándano rojo',
  cranberries: 'arándanos rojos',
  berries: 'moras',
  cherry: 'cereza',
  cherries: 'cerezas',
  peach: 'durazno',
  peaches: 'duraznos',
  pear: 'pera',
  pears: 'peras',
  plum: 'ciruela',
  plums: 'ciruelas',
  prunes: 'ciruelas pasas',
  apricot: 'chabacano',
  apricots: 'chabacanos',
  nectarine: 'nectarina',
  mango: 'mango',
  mangos: 'mangos',
  papaya: 'papaya',
  papayas: 'papayas',
  pineapple: 'piña',
  guava: 'guayaba',
  guavas: 'guayabas',
  kiwi: 'kiwi',
  kiwifruit: 'kiwi',
  melon: 'melón',
  melons: 'melones',
  cantaloupe: 'melón',
  watermelon: 'sandía',
  avocado: 'aguacate',
  avocados: 'aguacates',
  raisins: 'pasas',
  dates: 'dátiles',
  figs: 'higos',
  olives: 'aceitunas',
  olive: 'oliva',
  plantain: 'plátano macho',
  plantains: 'plátanos machos',
  juice: 'jugo',
  juices: 'jugos',
  // Vegetables
  vegetable: 'vegetal',
  vegetables: 'verduras',
  potato: 'papa',
  potatoes: 'papas',
  tomato: 'jitomate',
  tomatoes: 'jitomates',
  onion: 'cebolla',
  onions: 'cebollas',
  garlic: 'ajo',
  carrot: 'zanahoria',
  carrots: 'zanahorias',
  broccoli: 'brócoli',
  cauliflower: 'coliflor',
  celery: 'apio',
  cucumber: 'pepino',
  cucumbers: 'pepinos',
  eggplant: 'berenjena',
  mushroom: 'champiñón',
  mushrooms: 'champiñones',
  pepper: 'pimiento',
  peppers: 'pimientos',
  chili: 'chile',
  chile: 'chile',
  chiles: 'chiles',
  jalapeno: 'jalapeño',
  jalapenos: 'jalapeños',
  lettuce: 'lechuga',
  spinach: 'espinaca',
  cabbage: 'col',
  kale: 'col rizada',
  chard: 'acelga',
  greens: 'hojas verdes',
  leaves: 'hojas',
  beets: 'betabel',
  radish: 'rábano',
  radishes: 'rábanos',
  turnip: 'nabo',
  turnips: 'nabos',
  asparagus: 'espárragos',
  artichoke: 'alcachofa',
  artichokes: 'alcachofas',
  okra: 'okra',
  zucchini: 'calabacita',
  squash: 'calabaza',
  pumpkin: 'calabaza',
  nopales: 'nopales',
  jicama: 'jícama',
  sprouts: 'germinados',
  summer: 'de verano',
  winter: 'de invierno',
  immature: 'inmaduro',
  mature: 'maduro',
  ripe: 'maduro',
  flesh: 'pulpa',
  // Sweets, sauces and drinks
  sugar: 'azúcar',
  sugars: 'azúcares',
  honey: 'miel',
  syrup: 'jarabe',
  molasses: 'melaza',
  maple: 'maple',
  sweetener: 'edulcorante',
  chocolate: 'chocolate',
  cocoa: 'cacao',
  candies: 'dulces',
  candy: 'dulce',
  gum: 'chicle',
  jam: 'mermelada',
  jelly: 'jalea',
  puddings: 'pudines',
  pudding: 'pudín',
  custard: 'natilla',
  gelatin: 'gelatina',
  dessert: 'postre',
  desserts: 'postres',
  ice: 'hielo',
  sherbet: 'nieve',
  vanilla: 'vainilla',
  cinnamon: 'canela',
  spices: 'especias',
  herbs: 'hierbas',
  salt: 'sal',
  sodium: 'sodio',
  mustard: 'mostaza',
  ketchup: 'cátsup',
  vinegar: 'vinagre',
  dressing: 'aderezo',
  mayonnaise: 'mayonesa',
  sauce: 'salsa',
  gravy: 'salsa',
  soup: 'sopa',
  soups: 'sopas',
  broth: 'caldo',
  stock: 'caldo',
  stew: 'guiso',
  oil: 'aceite',
  shortening: 'manteca vegetal',
  lard: 'manteca',
  beverages: 'bebidas',
  beverage: 'bebida',
  drink: 'bebida',
  drinks: 'bebidas',
  water: 'agua',
  soda: 'refresco',
  cola: 'cola',
  lemonade: 'limonada',
  tea: 'té',
  coffee: 'café',
  wine: 'vino',
  beer: 'cerveza',
  liquor: 'licor',
  whiskey: 'whisky',
  vodka: 'vodka',
  rum: 'ron',
  tequila: 'tequila',
  energy: 'energética',
  sports: 'deportiva',
  // Baby and diet
  babyfood: 'comida para bebé',
  infant: 'infantil',
  formula: 'fórmula',
  toddler: 'niño pequeño',
  junior: 'junior',
  nutrition: 'nutrición',
  dietary: 'dietético',
  protein: 'proteína',
  vitamin: 'vitamina',
  vitamins: 'vitaminas',
  calcium: 'calcio',
  iron: 'hierro',
  acid: 'ácido',
  ascorbic: 'ascórbico',
  calorie: 'caloría',
  calories: 'calorías',
  supplement: 'suplemento',
  // Meals and snacks
  snacks: 'botanas',
  snack: 'botana',
  snackfood: 'botana',
  bar: 'barra',
  bars: 'barras',
  breakfast: 'desayuno',
  lunch: 'comida',
  dinner: 'cena',
  meal: 'comida',
  entree: 'plato fuerte',
  entrees: 'platos fuertes',
  salad: 'ensalada',
  salads: 'ensaladas',
  foods: 'alimentos',
  food: 'alimento',
  product: 'producto',
  products: 'productos',
  pack: 'paquete',
  package: 'paquete',
  frankfurter: 'salchicha',
  frankfurters: 'salchichas',
  chinese: 'chino',
  italian: 'italiano',
  french: 'francés',
  mexican: 'mexicano',
  japanese: 'japonés',
  american: 'americano',
  spanish: 'español',
  original: 'original',
  classic: 'clásico',
  new: 'nuevo',
  us: 'EE. UU.',
  usda: 'USDA',
  program: 'programa',
  distribution: 'distribución',
  commodity: 'suministro',
  ready: 'listo',
  frozen_dessert: 'postre congelado',
  heat: 'calor',
  table: 'mesa',
  king: 'rey',
  northern: 'del norte',
  southern: 'del sur',
  volume: 'volumen',
  equal: 'igual',
  solution: 'solución',
  removed: 'retirado',
  off: 'quitado',
  on: 'con',
  a: 'a',
  the: 'el',
};

const CAPITALIZED = /^[A-Z]/;

function translateWord(word: string): string {
  const key = word.toLowerCase();
  // Hyphenated expressions ("ready-to-eat") arrive as one token.
  return WORDS[key] ?? PHRASES[key] ?? word;
}

/** Translates one comma-separated segment, longest phrases first. */
function translateSegment(segment: string): { text: string; translated: number } {
  const tokens = segment.split(/\s+/).filter(Boolean);
  const out: string[] = [];
  let translated = 0;
  for (let i = 0; i < tokens.length;) {
    let matched = false;
    for (let length = Math.min(5, tokens.length - i); length >= 2; length--) {
      const phrase = tokens
        .slice(i, i + length)
        .join(' ')
        .toLowerCase();
      const hit = PHRASES[phrase];
      if (hit !== undefined) {
        out.push(hit);
        translated += length;
        i += length;
        matched = true;
        break;
      }
    }
    if (matched) continue;
    const token = tokens[i]!;
    // Keep punctuation around the word ("(cooked)", "salt,").
    const match = /^([^\w]*)([\w'&-]+)([^\w]*)$/u.exec(token);
    if (!match) {
      out.push(token);
      i++;
      continue;
    }
    const [, before = '', word = '', after = ''] = match;
    const result = translateWord(word);
    if (result !== word) translated++;
    out.push(`${before}${result}${after}`);
    i++;
  }
  return { text: out.join(' '), translated };
}

export interface Translation {
  text: string;
  /** Share of words that had a translation (0..1). */
  coverage: number;
}

/**
 * Translates a USDA food name such as "Chicken, broilers or fryers, breast, meat only,
 * cooked, roasted" into "Pollo, de engorde, pechuga, solo carne, cocido, asado".
 * Brand names in capitals (KELLOGG'S, MCDONALD'S) are left untouched.
 */
export function translateName(name: string): Translation {
  const segments = name.split(',').map((segment) => segment.trim());
  let words = 0;
  let translated = 0;
  const parts = segments.map((segment) => {
    if (segment === '') return '';
    // All-caps segments are brands or product names.
    if (segment.length > 2 && segment === segment.toUpperCase() && CAPITALIZED.test(segment)) {
      words += segment.split(/\s+/).length;
      return segment;
    }
    const result = translateSegment(segment);
    words += segment.split(/\s+/).filter(Boolean).length;
    translated += result.translated;
    return result.text;
  });
  let text = parts.join(', ');
  text = text.charAt(0).toUpperCase() + text.slice(1);
  return { text, coverage: words === 0 ? 0 : translated / words };
}
